### ISSUE TITLE
Token Library

### ISSUE THREAD

**Issue by JosephSamela** [dungeon-revealer/dungeon-revealer#604] opened 2020-07-20 13:38 UTC
An enhancement could be a "Token Library".

![token-library](https://user-images.githubusercontent.com/16111451/87941905-d3ae1700-ca69-11ea-9728-2e5cd9cb513c.png)

It would look the same as the Map Library, but instead of creating maps you create a palette of tokens. Each token has a name, color, size, graphic (I'm assuming #603), visibility, etc.

![token library](https://user-images.githubusercontent.com/16111451/87942997-6b603500-ca6b-11ea-8225-aaf9ee3e859e.png).

Then when you need a token, you open the Token Library, click the token and place it on the map. The current implementation of dropping generic tokens from the sidebar would not change.

**Comment by JosephSamela** [comment] 2020-07-20 13:39
This could also satisfy #573 by allowing multiple selections from the Token Library. For example, where you click a library token multiple times it selects multiple tokens. Perhaps a counter could appear "x4". When you place them on the map all selected tokens are placed near each other. The DM would be expected to arrange them more precisely.

**Comment by n1ru4l** [comment] 2020-07-20 16:09
I am going to close this as a duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/260

I copied your contents over there! Feel free to add additional information over there!

**Closed by n1ru4l** 2020-07-20 16:09 UTC
Labels: enhancement
