### ISSUE TITLE
Support for animated maps

### ISSUE THREAD

**Issue by GoOz** [dungeon-revealer/dungeon-revealer#433] opened 2020-05-11 14:05 UTC
It would be cool if we could use animated maps like the ones done by Dynamic dungeons and such. 
The raw map files are heavy (it's supposed to be used locally on a horizontally disposed screen) but I can get to less than 10mb by re-encoding them with webm VP9 codec and that would make great maps for players to play on.

**Comment by n1ru4l** [comment] 2020-05-25 21:02
duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/433

**Closed** 2020-06-07 18:33 UTC
Labels: enhancement, help wanted
