### ISSUE TITLE
Token graphics

### ISSUE THREAD

**Issue by JosephSamela** [dungeon-revealer/dungeon-revealer#603] opened 2020-07-20 13:14 UTC
Today tokens are colors with text.

![image](https://user-images.githubusercontent.com/16111451/87941131-a6149e00-ca68-11ea-98fc-0af70136c1fc.png)

It would be fun to add graphics!

![gobiln-token](https://user-images.githubusercontent.com/16111451/87941308-f4c23800-ca68-11ea-89c8-a9590487fc85.png)

Thoughts?

**Comment by n1ru4l** [comment] 2020-07-20 16:15
Gonna close this as a duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/603. Please take a look at that issue for a more detailed answer 😊.

**Closed by n1ru4l** 2020-07-20 16:15 UTC
Labels: enhancement
