### ISSUE TITLE
README mentions DATA_DIR, which does not exist

### ISSUE THREAD

**Issue by jonhoo** [dungeon-revealer/dungeon-revealer#388] opened 2020-04-28 16:28 UTC
I think it should say `DATA_DIRECTORY` per https://github.com/dungeon-revealer/dungeon-revealer/pull/330 ?

**Comment by n1ru4l** [comment] 2020-04-29 06:26
The context is docker related, but you are right, there are some configuration options that are currently only documented in the GitHub releases. 

Would be awesome if anyone could gather them and add an overview table to the README/or der docs folder.

**Comment by jonhoo** [comment] 2020-04-29 13:28
Ohh, I missed that, you're right. Yeah, I guess this is really "the supported environment variables aren't documented".

**Comment by n1ru4l** [comment] 2020-05-01 07:47
Duplicate of #362

**Closed by n1ru4l** 2020-05-01 07:47 UTC
