### ISSUE TITLE
Additional Drawing Layer

### ISSUE THREAD

**Issue by ChriD** [dungeon-revealer/dungeon-revealer#1259] opened 2021-04-29 19:54 UTC
It would be nice to have a "drawing layer" wher the dm can draw simple stuff for e.g hidden doors.
I can use tokens for now as a workaround

**Comment by n1ru4l** [comment] 2021-04-30 17:51
Duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/1259

**Closed by n1ru4l** 2021-04-30 17:51 UTC

**Comment by maxb2** [comment] 2021-04-30 17:58
This *is* #1259 😂

**Comment by n1ru4l** [comment] 2021-04-30 18:03
😂 😂 😂 

Duplicate of https://github.com/dungeon-revealer/dungeon-revealer/issues/23
