### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by TROY3269** [dungeon-revealer/dungeon-revealer#669] opened 2020-08-23 06:25 UTC
Hey guys, Just wanted to say a big thank you , Used all the new features this weekend , and the product is great. 
1. Macros good , Would love If statements
2. Player movable icons great 
3. Would love tokens
4. love a drawing feature on the map to show players things.

**Comment by maxb2** [comment] 2020-08-23 21:44
Duplicate of #23 and #173.

Could you give an example of how you would want to use an if statement in a macro? Check out #637 for some incoming dice notation.

We have a [discord server](https://discord.com/invite/dS5khqk) too.

**Comment by n1ru4l** [comment] 2020-08-25 09:08
Hey @TROY3269, thank you for using the dungeon-revealer 😊. Since there are already issues for two of your mentioned points I am going to close this issue as we try to have precise issues that focus on one improvement/bug. Please feel free to open a new issue regarding macros and logics inside macros.

As @maxb2 mentioned feel free to also join us on Discord so we can chat a bit about it before making a concrete issue (however this is not required 😊).

**Closed by n1ru4l** 2020-08-25 09:08 UTC
