### ISSUE TITLE
Maps get reset

### ISSUE THREAD

**Issue by swingtempo** [dungeon-revealer/dungeon-revealer#1625] opened 2022-06-26 23:09 UTC
Sometimes I lose my maps. I deployed this app to heroku using the button in GitHub page, and I can upload fine. It also works fine but eventually maybe after a few hours everything disappears and I need to re upload it.

**Comment by maxb2** [comment] 2022-06-27 12:26
That is because Heroku does not save the state of your app. They expect the app to store this elsewhere. You can see more details at #405. As of now, the Heroku button serves more as a user demo than a permanent hosting solution.

Closing as a duplicate of #405

**Closed by maxb2** 2022-06-27 12:26 UTC
